AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Lint/NonLocalExitFromIterator:
  Enabled: false
